/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import pck.AuthenticationException_Exception;
import pck.FlightInfo;
import pck.Route;
import pck.Ticket;

/**
 *
 * @author Gerard
 */
public class BookPanel extends javax.swing.JPanel {

    private ClientFrame frame;
    private Route route;
    private Ticket ticket;
    
    /**
     * Creates new form BookPanel
     */
    public BookPanel(ClientFrame frame, Route route) {
        initComponents();
        this.frame = frame;
        this.route = route;
       
        ticketIdTextField.setVisible(false);
        ticketButton.setEnabled(false);
        messageLabel.setVisible(false);
        messageLabel.setForeground(Color.green);

        //Initialize BookTextInfo
        String content = getRouteContent(route);
        bookTextField.setText(content);
        bookTextField.setEditable(false);

    }
    
    public String getRouteContent(Route r){
        Double price=0.0;
        String content="";
        content+="From: "+r.getFrom()+"  To: "+r.getTo()+"\n";
        content+="Date: "+r.getFlightsOfRoute().get(0).getDate().toString()+"\n";
        content+="Flights details: \n";
        for(FlightInfo fi : r.getFlightsOfRoute()){
            content+="Idententifier: "+fi.getId()+"\n";
            content+="Price: "+fi.getPrice()+"\n";
            price+=fi.getPrice();
        }
        priceLabel.setText(price.toString());
        return content;
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        payButton = new javax.swing.JButton();
        cardNumberTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bookTextField = new javax.swing.JTextField();
        ticketButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ticketIdTextField = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();

        payButton.setText("Pay");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        cardNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Book flight");

        jLabel2.setText("Credit card number:");

        jLabel5.setText("Flight Book Service");

        ticketButton.setText("Tickets");
        ticketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Issue tickets");

        jLabel3.setText("Ticket identificator:");

        ticketIdTextField.setText("ticketID");

        messageLabel.setText("Ticket successfuly payed. Click Tickets to issue you ticket.");

        jLabel4.setText("Total price:");

        priceLabel.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookTextField)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ticketIdTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                        .addComponent(ticketButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cardNumberTextField)
                        .addGap(18, 18, 18)
                        .addComponent(payButton))
                    .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(priceLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(priceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cardNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messageLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketButton)
                    .addComponent(jLabel3)
                    .addComponent(ticketIdTextField))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed

        // TODO add your handling code here:
        final String cardNumber = cardNumberTextField.getText();

        Thread th = new Thread(new Runnable() {
            @Override
            public void run() {
                
                String date = route.getFlightsOfRoute().get(0).getDate().getDay()+"/"+
                    route.getFlightsOfRoute().get(0).getDate().getMonth()+"/"+
                    route.getFlightsOfRoute().get(0).getDate().getYear();

                try {
                    ticket = Controller.book(route.getFrom(), route.getTo(), route.getFlightsId(), date, cardNumber, Controller.tokenId);
                    ticketIdTextField.setText(ticket.getId());
                    ticketIdTextField.setVisible(true);
                    ticketButton.setEnabled(true);
                    payButton.setEnabled(false);
                    cardNumberTextField.setEditable(false);
                    messageLabel.setVisible(true);
                } catch (AuthenticationException_Exception ex) {
                    Logger.getLogger(BookPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }//GEN-LAST:event_payButtonActionPerformed

    private void cardNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumberTextFieldActionPerformed

    private void ticketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketButtonActionPerformed
        // TODO add your handling code here:
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                frame.setContentPane(new TicketPanel(frame, ticket));
                frame.validate();
            }
        });

                                                
    }//GEN-LAST:event_ticketButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookTextField;
    private javax.swing.JTextField cardNumberTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JButton payButton;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JButton ticketButton;
    private javax.swing.JLabel ticketIdTextField;
    // End of variables declaration//GEN-END:variables
}
